server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: turf-management-system
  
  # Redis Configuration
  data:
    redis:
      host: redis-10823.c262.us-east-1-3.ec2.redns.redis-cloud.com
      port: 10823
      password: TMlM7BqlkyG1lPdkdIIvDKWkP1Mr4BI5
      database: 0
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# Logging Configuration
logging:
  level:
    com.turfmanagement: DEBUG
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# CORS Configuration
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*" 